### ISSUE TITLE
Option to run under xinetd

### ISSUE THREAD

**Issue by linuxdan** [ghoneycutt/puppet-module-nrpe#39]
Add option to run nope under xinetd rather than its own daemon.

I can provide additional code for RedHat/CentOS and Debian/Ubuntu, but I have no access to Suse or Solaris

**Comment by ghoneycutt** [comment]
What changes are needed? I think you could write a small meta-module that included nrpe and xinetd and used xinetd::service for nrpe. I'm happy to get this working under xinetd with you.

``` puppet
class { 'nrpe':
  service_ensure => stopped,
  service_enable => false,
}

include xinetd

xinetd::service { 'nrpe':
  ...
}
```

https://github.com/puppetlabs/puppetlabs-xinetd

**Comment by ghoneycutt** [comment]
It seems like the only point of using xinetd is to have TCP wrappers, though I would just use the NRPE daemon and iptables to control access. Curious, why you use xinetd as I'm likely missing something?

**Comment by linuxdan** [comment]
Thanks for responding.  I have had very good luck using your modules.  I am please to try and improve one.

My searching about on the forums and blogs seems to indicate a slight preference to running nope under xinetd rather than on its own, but I am having a tough time finding justification.   My personal justification is "Because that's the way they do it here" (where I am currently working).  Refer to "Tradition" over at despair.com for my opinions on that.

A few other issues with "The Local Practice":
The first is that they use a bunch of home-grown scripts in the `libexec` directory.   Your module appears to only use a package resource to support a plugin/command.  So that says I either need to roll up all these scripts into packages or hack the module to include the option to push a file resource.

The other urgent issue is that they have "sudo" prefixing SOME of the commands, not all.  The `command_prefix` option does not seem to be selective.  This would be a second hack to add, or I can add `sudoer` code to handle those specific commands. 

If I find more details, I will share them.

**Comment by linuxdan** [comment]
Got an idea: I am going to try and get what I need by writing a composite wrapper class that can take care of both the `xinetd` and other issues.  This might work much easier than futzing inside this module.

Stay tuned.  Film @ 11 :smiling_imp:

**Comment by ghoneycutt** [comment]
@linuxdan Glad you enjoy my modules. If you want to stay up to date, I suggest using the Puppetfile from https://github.com/ghoneycutt/puppet-modules and subscribing to that repo to see changes.

Would strongly urge you to create a package for the scripts as they should not be in the repo with the module, the reasoning is that they are variable, site specific, and will likely contain binaries at some point which should not be in VCS. Also by keeping them separate you do not have them tightly coupled. So perhaps a different team that manages monitoring can contribute to the scripts which could be different than those doing the puppet work.

What I do is keep them in their own repo and then create a build script that will call FPM (https://github.com/jordansissel/fpm/) to create the package and place it somewhere useful, like your rpm/apt/whatever package repo's. You can make it part of a build pipeline or do it very simply with a git post-commit script.

Here's an example that I helped with

https://github.com/Ericsson/package_nagios_plugins
