### ISSUE TITLE
Support for raspbian (debian Jessie on Raspberry pi)

### ISSUE THREAD

**Issue by delinuxspecialist** [ghoneycutt/puppet-module-nrpe#53]
Could you please add support for raspbian (i.e. debian jessie on a raspberry pi) ?
I get the following error message : 
nrpe supports lsbdistid's Debian and Ubuntu in the osfamily Debian. Detected lsbdistid is <Raspbian>. at /etc/puppet/environments/production/modules/nrpe/manifests/init.pp:130 on node

Thanks,

    Michel van Deventer

**Comment by ghoneycutt** [comment]
Could you please paste the output of `facter`. That should give me the info needed to add support for Raspbian.

**Comment by ghoneycutt** [comment]
@delinuxspecialist I added support by just assuming things were the same in Debian 8 as Debian 6. Package names, paths, etc may have changed since then. Could you please test it out and let me know if it works for you.

https://github.com/ghoneycutt/puppet-module-nrpe/pull/55

**Comment by delinuxspecialist** [comment]
Works fine, paths are the same. It might be wise to add a line to your readme which states that the default nagios-nrpe-server is compiled without support for dont_blame_nrpe, it cannot be switched on unless you recompile the package nagios-nrpe-server yourself. See also https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=756479

Thanks for your effort ! :)

   Regards,

   Michel
